### ISSUE TITLE
Console log message every time a page loads

### ISSUE THREAD

**Issue by fstorr** [matatk/landmarks#107]
On pages with landmarks, dev tools shows a console log message of "Landmarks: took {time} to find landmarks on {URL details} {time} after booting {(n attempts)}".

**Comment by matatk** [comment]
This is by design in 2.0.8 (it may also be present in 2.1.0 when that is released). I added it because I'm making some big changes to how landmarks are found, and I wanted to make it easy for people to help collect real-world data on sites they use, if that became necessary. It shouldn't be causing you any problems—though if it is, please let me know.

**Comment by fstorr** [comment]
Thanks for the reply. It would be really helpful if this was configurable so that I don't see the message when I'm developing. I don't need to know how fast the extension works every time I refresh a page :)

**Comment by matatk** [comment]
Fair enough. I did think about making it configurable, but then that exposes technical details to the end-user. If, during testing, it seems that good performance has been achieved all-round with the new system, then I should be able to simply remove them.  Either way, expect them to be removed by default at least in 2.1.0.
