### ISSUE TITLE
Jumping to an off-screen landmark scrolls to the middle of the element

### ISSUE THREAD

**Issue by quasicomputational** [matatk/landmarks#147]
If the landmark being scrolled to is entirely off-screen, then the scroll target is somewhere in the *middle* of the target element. This is bad if the landmark element is very long and you're dropped into its guts without any context. The scroll target should probably be the top of the landmark element, even if that means scrolling up. Note that this doesn't happen if any portion of the landmark element is on-screen when you jump to it, which makes this extra surprising!

**Comment by matatk** [comment]
I had noticed that the current behaviour has some peculiarities, but not really looked into it too much, so thank you for quantifying exactly what's odd about it. So far I've stuck to the browser's default focusing/scrolling behaviour, for consistency and simplicity.

However, I agree that it's somewhat unhelpful and jarring when navigating to big landmark regions, so perhaps it's time to address this. I sense that the solution would involve placing an element in the document in order to be able to control where the focus goes. This will have to work with/without the new labelling planned for 2.2.0 (probably it will be completely separate). I also need to think about cleanup of any inserted elements.

One workaround that can be used, depending on the site, is to navigate to the big landmark, then back to the previous one and you are usually then at/near the top of the big one. I hope that helps in the meantime.

My expectation was that 2.2.0 would be the next release, but that will be quite some time off, as it's a big one. I will think about this issue and, if I can do it quickly, I might make another 2.1.x release which address it, particularly if it's causing you or others significant problems.

**Comment by matatk** [comment]
I have just tried it out on http://matatk.agrip.org.uk/landmarks/ and I have found a couple of interesting things. It's important to note that this page does **not** have a landmark that is completely off-screen, but what I did find about the default focusing behaviour actually seems pretty useful (more on the bug you actually raised below)...

**On Chrome and Firefox:**
- Moving forward between landmarks always ensures that the **top** of the landmark is visible on-screen.
- Moving backward between landmarks always ensures that the **bottom** of the landmark is visible on-screen.

This behaviour seems reasonable. It doesn't seem wise to assume that, when moving backward between landmarks, the user wants to jump right to the **top** of the previous one—that would mean that a big jump to a different area of the page would occur, which is the problem you highlighted with off-screen landmarks. It sounds like I should take into account this top/bottom anchor point when focusing in a given direction when implementing something for off-screen landmarks.

I've actually struggled to find a page that has a landmark that is **completely** off-screen until focused; could you suggest one (or some)? It would be good to try this out on the same pages you've been using.

**Comment by quasicomputational** [comment]
I was testing out some local private documents when I noticed this; they're very much document-shaped, with frontmatter and introductory stuff before the main content. [Here is a marked-up version of the (start of) the 1898 edition 'A Tale of Two Cities'](https://gist.github.com/quasicomputational/8abc8ee6e6255c6260ad72ffd148c2e1), which shows the same effect: the lengthy introduction is part of the `contentinfo` landmark, which pushes the `main` landmark a way off-screen (and the first chapter's long enough that being dropped in the middle of it is quite different to being at the start). It's not marked up, but [here's a BMJ article where you'd see the same effect](http://www.bmj.com/content/355/bmj.i5432), if they wrapped the article itself in `<main>`.

**Comment by quasicomputational** [comment]
Ah, here we go. I knew one of the big publishes-in-HTML houses would have a direct example: [an article](https://www.nature.com/articles/mp2017124) with a 'References' `region` that's well off-screen, and quite long.

**Comment by quasicomputational** [comment]
As for solutions: just calling `scrollIntoView()` on the target element before focussing suffices if we always want to go to the top. Going to the top is what I'd expect anyway, so I'd be happy with that.

Alternatively, `scrollIntoView` takes a boolean argument telling it to go to the top or the bottom, so recovering the current behaviour is possible, but I'm not 100% convinced that that's a feature and not a 'feature'.

I'd agree that being able to go to the end of a landmark might be occasionally useful (when the end of one landmark doesn't coincide perfectly with the start of the next), but I'd then suggest it makes more sense to have that as a separate action rather than depending on the direction that you're going through the landmarks. I don't object to big jumps *per se*, but to being dropped in the middle of things and then having to look for a defined start/end point to figure out where I am.

**Comment by matatk** [comment]
I've not had the cycles to work on this lately, and it's probably about a week away, but wanted to update you on this: I have been trying it out, and I agree that on balance it seems best to scroll to the top of the landmark, so that's what I plan to implement :-).

**Comment by matatk** [comment]
As with #148, I've implemented this and it's available [to try out](https://github.com/matatk/landmarks#development). Will make a new release with this in soon.
