### ISSUE TITLE
How to disable display help.html page

### ISSUE THREAD

**Issue by notiv-nt** [matatk/landmarks#310]
Every time you update an extension, remove it

**Comment by notiv-nt** [comment]
Stop opening some pages for me.
Bring these changelogs here
![Screenshot 2019-03-26 at 11 10 34 AM](https://user-images.githubusercontent.com/10743009/54980877-f9cbc000-4fb7-11e9-91af-aa21e2001485.png)

**Comment by matatk** [comment]
Thank you for your feedback, and sorry for my slow reply.

I see that an unexpected help page appearing could be annoying if it happened often - but I am trying to balance that and the need to provide important information to users, particularly Chrome/Opera users.

# Why the help page appears

Many extensions open a page when they are updated, so that they can explain important changes and new features to users. Landmarks has always done this, and the help page has become even more useful lately, as it provides important information for users.

It looks like you’re using Chrome, and on Chrome particularly, the help page is needed to explain to users that, due to Chrome limitations, they may need to set some of their own keyboard shortcuts.

My concern with not automatically showing the help page is that users may not notice this information and would miss out on features as a result.

I realise that there have been several updates recently. This was because some big improvements were made to the code that also involved big changes and, as a result, some bugs crept through. I am working hard on making that less likely in future.

# What could be done

## Fewer releases 

I think, for now, the best thing to do would be to aim to make releases less often, which is what I am planning to do anyway.

## Banner instead of help page [not currently possible]

I think you are suggesting that a banner should be placed at the bottom of the page to alert users to important updates. Unfortunately the WebExtensions API doesn’t provide a standard way to do this.

There are workarounds that mean it could be done on some, but not all pages, and as a result it would probably not provide a good user experience.

## Notifications in pop-up/sidebar

I could place notifications of the keyboard shortcut limitations/warning and any important new features in the pop-up/sidebar directly. The toolbar icon could be badged with an exclamation mark too.

However this would take some development effort to set up, and may overwhelm new users with too much information after the first install. It’s much easier to close the help page once than lots of notifications.

Alternatively maybe there could be just one notification: for the user to check out the new features on update.

This would result in the user having to open the help page anyway though, in order to clear the “!” from the toolbar badge. Plus I’d be concerned that some users wouldn’t be able to see the badge clearly enough to appreciate the warning about new information they may need to know.

# Summary

I understand the potential problem, and will be mindful of it in future. I’m not sure there’s a clear solution at the moment, other than making releases less often.

My development time is limited and there are higher-priority tasks at the moment, but I’ll be thinking about this, and if I can find a clear way to improve it I’ll give it a go.

**Comment by matatk** [comment]
Closing this for now, but I will continue to think about what can be done to improve thengs, in line with [my comment above](https://github.com/matatk/landmarks/issues/310#issuecomment-480446977). Thanks again for your feedback.

**Comment by matatk** [comment]
I came across the [HeadingsMap extension](https://github.com/dzc34/headingsMap) this week (which looks rather good), and realised I could use a similar technique—badging the browser toolbar button—to indicate when there's been an update, and have been working on it.

In the code I'm working on, Landmarks will still open its help page when installed, but when there has been an update, it will put a badge on the toolbar button, and a note in the pop-up/sidebar. I think this will address your concerns, yet still provide the information clearly.
