### ISSUE TITLE
Can you extend this to HTML Headings please?

### ISSUE THREAD

**Issue by BillDashfield** [matatk/landmarks#420]
Great plugin - this is is not to report an Issue but to request an enhancement, for keyboard shortcuts to navigate by HTML Heading. 

As far as I (and [WCAG](https://github.com/w3c/wcag/issues/1712)) can find out, there is no plugin for keyboard navigation using HTML headings for Chrome/Firefox/Edge or Safari (already built in to Opera ).

There is a need for this facility. Sighted non-mouse/keyboard-only users can navigate using Landmarks (if they exist on the website), or by tabbing from link to link which is very tedious and slow going through large menus (if there are no skip links as is often the case).  Page or Arrow keys to scroll up or down works for browsing, but if you then want to follow a link or fill in a form, Tab takes you right back to the start of the page, as scroll does not move the active field/focus, and you have to Tab through the menus and content again.

A browser plugin that allows navigation with keyboard shortcuts would be of enormous value to people who by disability or preference do not use a mouse, and also to web-site accessibility testers.  Many people (including myself) would be very grateful. 

If you do this, I think it would need to set Focus on the next link/form field after the header, as well as positioning the display on the relevant heading.  

I suggest you use the following key combinations by default, as they are the same as used by the popular NVDA screen reader: H,1,2,3,4,5,6 to go to the next heading, or to the next level 1,2,3,4,5 or 6 heading. Shift+H,1,2,3,4,5,6 to go back to the previous heading, or the previous level 1,2,3,4,5 or 6 heading. Giving the user the ability to choose different shortcut keys would also be desirable.

Many thanks for your plugin and for considering this request,

Cheers
Bill

**Comment by matatk** [comment]
Hi Bill, and thanks for your feedback and suggestion. Glad you are finding the extension useful. I have been thinking about how best to include headings for a while (#156) and your comments remind me this is important. It is also surprisingly hard to get right from a UX and performance perspective (particularly given the constraints of the browser extension environment), but I think I have answers to some of those challenges now, at least. I am very interested in supporting heading navigation.

Regarding the shortcut keys, I agree that the ones you propose are ideal, but there are some constraints on the shortcut keys that browser extensions can define and use—and there is a lot of potential for keys to clash with existing browser/OS shortcuts. That's why the default keys for navigating landmarks are... a bit cumbersome. However I would of course make it possible for users to set their own shortcuts (within the limits of browser extensions). Some of the considerations around this are noted (a bit haphazardly) in #156.

You can use the very helpful [a11y-outline extension](https://github.com/xi/a11y-outline) by @xi to navigate headings via the keyboard right now (use Ctrl+Shift+7 or Command+Shift+7 on Mac to bring up the navigation dialog once it's installed).

**Comment by kimviens** [comment]
Have you heard of the extension [Headings Map](https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi)?

**Comment by matatk** [comment]
HeadingsMap is good (the above link is to Chrome; you can also get [HeadingsMap for Firefox](https://addons.mozilla.org/en-GB/firefox/addon/headingsmap/)). There's also @xi's [a11y-outline](https://github.com/xi/a11y-outline) too.

I have been (and still am) working on infrastructure to improve the performance of monitoring pages for changes. I hope to finally add headings support to this extension not long after that's done. But you can use the above two great tools already :-).
