### ISSUE TITLE
Mutation Observer does not seems to work correctly

### ISSUE THREAD

**Issue by cbou** [matatk/landmarks#458]
On my app the roles that are set with JavaScript later after the page load are not detected by the plugin.

I look at the code and found out that you use a MutationObserver which should be used in this case.

Actually this does not seems to work.
Following is a HTML page which define a landmark after 2 seconds.

The landmark won't be detected by the plugin.
If you click on another tab and then back to this dummy page then the landmark will be find.

Is that the expected behaviour?

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World! Site Title</title>
  </head>
  <body>
    <div class="foo">
      <h1>Hello World!</h1>
    </div>
    <script>
      setTimeout(() => {
        document.querySelector('.foo').setAttribute("aria-label", "bar")
        document.querySelector('.foo').setAttribute("role", "banner")
        alert('Landmarks added')
      }, 2000)
    </script>
  </body>
</html>
```

**Comment by matatk** [comment]
I made a separate, minimal browser extension to try and track the problem down, and I was able to get it to work with your example code (i.e. the mutations were detected by the extension's content script).

Looks like this problem was introduced [in a change to the content script](https://github.com/matatk/landmarks/commit/94d06dff39736d3f3fe7bbbc4c65a5a83978afab#diff-52093e1d0106617c7f4254295d45bb398863ccd9b77090750331fe6372e69d92L279) that is causing mutations to only be observed after the page is hidden and then re-shown; quite a big mistake—oh dear! Thanks again for raising this, and providing a clear and minimal example.

I've often thought it would be good to have tests for at least some key behaviours of the extension (to go alongside the existing tests for the accuracy of scans), but the effort of mocking the whole extension environment would be very great, and I haven't figured out a way to test parts in a more isolated fashion. On the plus side, this code changes very rarely, and I put in a lot of logging; will aim to strengthen that and test it for longer in future.

There are a couple of details I'm still working out for this, but I will fix it as soon as possible.
