### ISSUE TITLE
Invisible controls on dark mode

### ISSUE THREAD

**Issue by anevins12** [matatk/landmarks#466]
Using a darkmode theme on Chrome results in white text on white background
<img width="305" alt="Untitled" src="https://user-images.githubusercontent.com/2318561/158477219-74052ad9-d4dc-4ddc-9184-d8f594623870.png">

**Comment by matatk** [comment]
Thanks for this @anevins12. I was able to reproduce it.

**Comment by matatk** [comment]
Thanks for reporting. I've fixed this (and it will soon be, though isn't yet, in an official release). Turns out it was affecting Edge and Opera too. I was using [`devtools.panels.themeName`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels/themeName) and the [`browser.devtools.panels.onThemeChanged`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels/onThemeChanged) event to detect when the DevTools theme changed, but have switched to using [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) directly in the DevTools panel's CSS now. Not sure if back when I first implemented this, the media query wasn't well-supported, but it certainly is now.

**Comment by matatk** [comment]
2.11.1 has been released and contains the fix for this bug. It's available in Firefox and Chrome now; Opera and Edge should follow in several days, after review. Thanks again for your report.
